/**
 * Gallery copy in both languages.
 *
 * The point of the Farsi column is not translation for its own sake: mirrored
 * English tests almost nothing. Real Persian text is what surfaces joined-form
 * damage from letterspacing, the leading a Latin-tuned scale gets wrong, digits
 * that should read ۰۱۲۳, and directional icons pointing the wrong way.
 *
 * Code snippets, token names and prop names stay Latin in both columns — they
 * are identifiers, not prose, and `docs.css` keeps them left-to-right.
 */
export type Lang = 'en' | 'fa'

const en = {
  dir: 'ltr' as 'ltr' | 'rtl',
  locale: 'en-GB',
  tagline: 'Design system & UI kit',
  bylinePrefix: 'designed and built by',
  author: 'Nima Sarayan',
  pages: { components: 'Components', flows: 'Flows', foundations: 'Foundations' },
  controls: { colorway: 'Colourway', language: 'Language', page: 'Page', scheme: 'Scheme', style: 'Style' },
  schemes: { dark: 'Dark', light: 'Light', system: 'System' },
  nav: {
    badge: 'Badge', button: 'Button', card: 'Card', color: 'Colour', composition: 'Composition',
    data: 'Data', density: 'Density', feedback: 'Feedback', focus: 'Focus', form: 'Form controls',
    input: 'Input', list: 'List', admin: 'Admin console', auth: 'Sign-in', chat: 'Chat', console: 'Console layer',
    checkout: 'Checkout', onboarding: 'Onboarding', progress: 'Long jobs', wizard: 'Wizard',
    plans: 'Plans', profile: 'Profile', tabbar: 'Tab bar',
    motion: 'Motion', navigation: 'Navigation', overlay: 'Overlays', shape: 'Shape & elevation',
    sheet: 'Sheet', space: 'Space', stat: 'Stat', type: 'Type',
    chart: 'Charts', map: 'Maps', player: 'Player',
    messenger: 'Messenger', assistant: 'Assistant',
    diagnosis: 'Diagnosis',
    evidence: 'Evidence',
  },
  t: {
    // intro
    introTitle: 'Components',
    introBody:
      'Every variant, size, and state the kit ships. Flip the style, colourway, scheme, or language in the bar above and read this page again — nothing below is re-authored per pairing.',
    spProvenance: 'A figure that says where it came from',
    spUnknownEmpty: 'Nothing here, and cannot see',
    ntProvenance: 'A console\u2019s figures are read as facts, so the ones that came from an instrument say where — and the ones that did not become conspicuous by not saying it. An unmeasured row is hatched rather than blank: a blank is ambiguous between "none" and "not asked", and both get read as data.',
    ntUnknownEmpty: 'Two different claims that most consoles render identically. A cluster with no stacks has no stacks; a cluster whose agent never answered has an unknown number of stacks. Rendering both as an empty table teaches operators that empty means none, and one day that reading is wrong expensively.',
    evNotMeasured: 'not measured',
    evEmptyTitle: 'No stacks', evEmptyBody: 'This Swarm schedules no stacks. The manager answered.',
    evUnknownTitle: 'Cannot see stacks', evUnknownBody: 'No manager answered, so the number of stacks is unknown rather than zero.',
    spLedger: 'Measured, and not evidence',
    spTrail: 'What a conclusion rested on',
    ntLedgerHonest: 'Most consoles put both halves in one grid, which invites the reader to average across them — and an absence averaged into a figure is how a dashboard reports a number nobody measured. On a fresh system the right column is longer than the left, and that is the honest first impression rather than a failure state.',
    ntTrailAge: 'Age is the substance, not metadata. A conclusion drawn from a five-minute-old reading is a guess wearing a fact\u2019s clothes, and listing the ages together is what lets a reader see the whole argument resting on stale ground.',
    evMeasured: 'Measured', evAbsent: 'Not evidence',
    evNodes: 'Nodes ready', evTasks: 'Task coverage', evMemory: 'Memory used',
    evCpu: 'CPU utilisation', evTraces: 'Traces',
    evSwarm: 'cluster manager', evProbe: 'read-only host probes',
    evWhyCpu: 'load average is not utilisation', evWhyTraces: 'no collector installed',
    evCoverage: '4/4 probes healthy',
    evTrailCaption: 'Every measurement this chain used, with when it was taken.',
    // diagnosis
    spCausalChain: 'A chain that shows its work',
    spCaveat: 'What is not known',
    spDiff: 'What moved',
    ntCausalStops: 'Every link carries the measurement behind it. A link with no evidence is drawn thinner on purpose — an unevidenced step is the one a reader should distrust, and the component must not disguise it.',
    ntCaveatQuiet: 'Hatching, not a tint: it survives greyscale, print, and a screenshot pasted into an incident channel. A caveat is not a warning — it says unmeasured, not wrong, and must not compete with real alarms.',
    ntDiffMarkers: 'The + and − are text, not colour alone. A diff distinguished only by red and green fails for roughly one man in twelve, and fails everywhere it gets pasted.',
    dgObserved: 'observed', dgBecause: 'because',
    dgClaim1: 'api-gateway is running 2 of 3 desired tasks.',
    dgClaim2: 'Task 3 has been pending for 6 minutes, so this is placement, not a crash.',
    dgClaim3: 'worker-03 has 1.4 GB free and the image needs 2.1 GB.',
    dgEv1: '2/3 tasks', dgEv2: 'no restart events', dgEv3: '1.4 GB free · 2.1 GB required',
    dgSrc1: 'swarm manager · 4s ago', dgSrc2: 'task history · 4s ago', dgSrc3: 'host probe · 22s ago',
    dgFix: 'Reclaim 3.2 GB by pruning 11 unused images.',
    dgCaveatTitle: 'What this cannot see',
    dgCaveatBody: 'The pull may also fail for registry-auth reasons, which cannot be tested without attempting it.',
    // button
    saveChanges: 'Save changes', startScan: 'Start scan', cancel: 'Cancel', skip: 'Skip',
    del: 'Delete', small: 'Small', medium: 'Medium', large: 'Large', saving: 'Saving',
    unavailable: 'Unavailable', newEntry: 'New entry', continueLabel: 'Continue',
    search: 'Search', settings: 'Settings', add: 'Add',
    // badge
    neutral: 'Neutral', accent: 'Accent', live: 'Live', pending: 'Pending', failed: 'Failed',
    info: 'Info', beta: 'Beta',
    // card
    cardDefault: 'Default', cardRaised: 'Raised', cardMuted: 'Muted', cardAccent: 'Accent',
    cardDefaultBody: 'A ruled plate on the canvas.',
    cardRaisedBody: "Carries the style's elevation.",
    cardMutedBody: 'Recedes behind its neighbours.',
    cardAccentBody: 'For a single highlighted item.',
    viewReport: 'View report', session: 'Session 04', complete: 'Complete',
    cardBody: "Composition is the card's job; spacing between cards belongs to the page.",
    // stat
    eventsPerMinute: 'Events per minute', latency: 'p99 latency', throughput: 'Throughput gain',
    costReduction: 'Cost reduction',
    // form
    email: 'Email', emailHint: 'We only use this to send the report.',
    findRoutine: 'Find a routine', fullName: 'Full name', fullNameError: 'This field is required.',
    workspace: 'Workspace', notes: 'Notes', notesHint: 'Markdown is supported.',
    notesPlaceholder: 'What changed?', cadence: 'Cadence', daily: 'Daily', weekly: 'Weekly',
    monthly: 'Monthly', chooseOne: 'Choose one', weeklySummary: 'Weekly summary',
    weeklySummaryDesc: 'Sent every Monday morning.', notOnPlan: 'Unavailable on this plan',
    reducedMotion: 'Reduced motion', reducedMotionDesc: 'Applies to this device only.',
    load: 'Load', range: 'Range', week: 'Week', month: 'Month', year: 'Year',
    // radio, chips, rating, upload, disclosure, timeline, data list
    spRadio: 'Radio group', ntRadio: 'A fieldset with a real legend — the question has to be announced before the answers.',
    rgDelivery: 'Delivery', rgStandard: 'Standard', rgStandardDesc: 'Three to five working days.',
    rgExpress: 'Express', rgExpressDesc: 'Next working day, before noon.',
    rgPickup: 'Collect in person', rgHint: 'Changeable until the order ships.',
    spChips: 'Chips & token input', ntChips: 'A chip is an object you can drop; a badge is a label about one.',
    chipRecipients: 'Recipients', chipHint: 'Enter or comma commits; backspace removes the last.',
    chipAdd: 'Add an address', chipRemove: 'Remove', chipFilters: 'Filters', chipUnread: 'Unread', chipFlagged: 'Flagged',
    chipArchived: 'Archived', chipOverdue: 'Overdue',
    spRating: 'Rating', ntRating: 'Radios behind stars, so arrow keys and form submission are the platform\u2019s.',
    ratingLabel: 'Rate this session', ratingStatic: 'Average of 128 ratings',
    spUpload: 'File drop', ntUpload: 'The zone is a label around a real file input; the upload itself stays the product\u2019s.',
    uploadLabel: 'Drop a receipt here', uploadPrompt: 'or click to choose a file',
    uploadCaption: 'PNG, JPG or PDF · up to 10 MB', uploadPicked: 'Selected',
    spAccordion: 'Disclosure', ntAccordion: 'The panel opens to its content\u2019s own height — a grid row, not a measured max-height.',
    accBilling: 'Billing', accBillingBody: 'Invoices are issued on the first of the month and settle against the card on file.',
    accSecurity: 'Security', accSecurityBody: 'Two-factor authentication applies to every member of the workspace.',
    accData: 'Data export', accDataBody: 'An export is prepared in the background and stays available for seven days.',
    accItems: '3 sections',
    spTimeline: 'Timeline', ntTimeline: 'An ordered list: the claim of a timeline is the order.',
    tlSubmitted: 'Receipt submitted', tlSubmittedAt: '23 Aug, 09:12',
    tlReview: 'Picked up for review', tlReviewAt: '23 Aug, 09:41',
    tlApproved: 'Approved', tlApprovedAt: '23 Aug, 10:02',
    tlSettled: 'Settled to the wallet', tlSettledAt: 'Pending',
    tlReviewBody: 'Assigned to the payments queue.',
    spDataList: 'Data list', ntDataList: 'A description list, because these labels describe these values — not a table pretending to be a grid.',
    dlPlan: 'Plan', dlPlanValue: 'Plus · billed yearly', dlSeats: 'Seats', dlSeatsValue: '12 of 20 used',
    dlRenews: 'Renews', dlRenewsValue: '1 March 2027', dlReference: 'Reference',
    // list
    profileSub: 'Signed in · nimax.sr@gmail.com', notifications: 'Notifications',
    notificationsSub: 'Daily at 08:00', appearance: 'Appearance', signOut: 'Sign out',
    openedProfile: 'Opened profile', openedNotifications: 'Opened notifications',
    signedOut: 'Signed out',
    // feedback
    scanQueued: 'Scan queued', scanQueuedBody: 'Results usually arrive within a minute.',
    newRelease: 'New in this release',
    newReleaseBody: 'Routines can now be shared with your clinician.',
    profileCurrent: 'Your profile is up to date.', connectionSlow: 'Connection is slow',
    connectionSlowBody: 'We will keep retrying in the background.',
    uploadFailed: 'Upload failed', uploadFailedBody: 'The file exceeded the 12 MB limit.',
    upload: 'Upload', working: 'Working', successToast: 'Success toast',
    changesSaved: 'Changes saved.', withAction: 'With action', undo: 'Undo',
    entryDeleted: 'Entry deleted.', addFirstRoutine: 'Add your first routine',
    noRoutines: 'No routines yet',
    noRoutinesBody:
      'Nothing has been recorded yet. Once you add a routine it will appear here with its history.',
    // sheet
    openSheet: 'Open sheet', confirmRoutine: 'Confirm routine', confirm: 'Confirm',
    sheetBody:
      "The sheet is the kit's modal surface. It locks the page behind it, closes on Escape, and returns focus to whatever opened it.",
    name: 'Name', eveningRoutine: 'Evening routine', remindMe: 'Remind me',
    // navigation
    workspaceCrumb: 'Workspace', billing: 'Billing', invoices: 'Invoices',
    open: 'Open', overdue: 'Overdue', paid: 'Paid',
    pageSummary: (page: number) => `Page ${page} of 14 · 84 invoices`,
    // overlays
    invoiceActions: 'Invoice actions', thisInvoice: 'This invoice', downloadPdf: 'Download PDF',
    sendToClient: 'Send to client', duplicate: 'Duplicate', voidInvoice: 'Void invoice',
    voidTitle: 'Void this invoice?', voidDesc: 'Invoice 2291 · Atelier Fatemifar · 4,200 EUR',
    voidBody:
      'Voiding keeps the invoice in the ledger with a zero balance and notifies the client. It cannot be undone — issue a credit note instead if the work was delivered.',
    keepIt: 'Keep it', adjustDue: 'Adjust due date', dueDate: 'Due date', apply: 'Apply',
    reconcile: 'Reconcile with bank', archiveTip: 'Archive — keeps it searchable',
    archive: 'Archive',
    // data
    client: 'Client', reference: 'Reference', status: 'Status', amount: 'Amount',
    // input
    quantity: 'Quantity', startTyping: 'Start typing a client name',
    noMatch: (query: string) => `No client matches “${query}”. Create it.`,
    // composition
    today: 'Today', all: 'All',
    compositionDesc: 'Everything below is kit output — the page only supplies rhythm.',
    yourMorning: 'Your morning', streak: 'Streak', days: 'days', adherence: 'Adherence',
    nextCheck: 'Next check', onTrack: 'On track', steps: '3 steps',
    routineBody: 'Cleanser, serum, and SPF — logged automatically after each scan.',
    completion: 'Completion',
    // Specimen labels — what each demo is showing.
    spAScreenAssembledFromTheKit: 'A screen assembled from the kit',
    spBanners: 'Banners',
    spBottomSheet: 'Bottom sheet',
    spBreadcrumb: 'Breadcrumb',
    spChoice: 'Choice',
    spCombobox: 'Combobox',
    spDateField: 'Date field',
    spDatePicker: 'Date picker',
    spCalendarSystem: 'Calendar system',
    ntJalali:
      'Jalali months, Persian digits, a week starting Saturday — and the value handed back is still an ISO Gregorian date.',
    ntPickerCompact:
      'The compact form: one field, the grid behind a button, and the other calendar underneath.',
    calGregorian: 'Gregorian', calJalali: 'Jalali', hearingDate: 'Hearing date',
    spCommandPalette: 'Command palette',
    spDialog: 'Dialog',
    spEmptyState: 'Empty state',
    spIconButton: 'Icon button',
    spLoading: 'Loading',
    spMenu: 'Menu',
    spMetrics: 'Metrics',
    spPagination: 'Pagination',
    spPopover: 'Popover',
    spProgressSkeleton: 'Progress & skeleton',
    spRows: 'Rows',
    spSegmented: 'Segmented',
    spSizes: 'Sizes',
    spSlider: 'Slider',
    spStepper: 'Stepper',
    spTable: 'Table',
    spTabs: 'Tabs',
    spTextInputs: 'Text inputs',
    spToast: 'Toast',
    spTones: 'Tones',
    spTooltip: 'Tooltip',
    spVariants: 'Variants',
    spStatesIcons: 'States & icons',
    spWithHeaderAndFooter: 'With header and footer',
    // Specimen notes — the one thing worth knowing about each demo.
    ntAMenuSGeometry: "a menu's geometry with a form's contents",
    ntARealDialogTop: 'a real <dialog> — top layer and focus trap from the platform',
    ntPaletteRanks: 'ranks by where the match landed · ↑↓ · Enter runs · the ⌘K that opens it belongs to the app',
    palOpenIt: 'Open the palette',
    palFindOrRun: 'Find a screen or run an action',
    palSearch: 'Search screens and actions…',
    palGoTo: 'Go to',
    palRun: 'Run',
    palInvoices: 'Invoices',
    palInvoicesHint: 'Everything issued, by client and by state',
    palClients: 'Clients',
    palClientsHint: 'Billing contacts, terms, and balances',
    ntASevenSlotWindow: 'a seven-slot window that never changes width',
    ntArrowKeysEscapeFocus: 'arrow keys · Escape · focus restored',
    ntHoverWaits200msFocus: 'hover waits 200ms · focus does not',
    ntLoadingKeepsTheLabel: 'loading keeps the label in place so the width never jumps',
    ntNoBespokeCss: 'no bespoke CSS',
    ntRowHeightFollowsNim: 'row height follows --nim-density',
    ntScrollLockEscapeFocus: 'scroll lock · Escape · focus restore',
    ntSwitchesARegionA: 'switches a region — a Segmented sets a value',
    ntTheLastCrumbIs: 'the last crumb is never a link',
    ntTwoControlHeightTargets: 'two control-height targets, not cramped chevrons',
    ntTypeToFilterEscape: 'type to filter · Escape reverts',
    ntTypingAlwaysWorksThe: 'typing always works; the calendar is the aid',
    // ── Chart ─────────────────────────────────────────────────────────
    spChartLine: 'Line and area', spChartBar: 'Bars', spSparkline: 'Sparkline',
    ntChart:
      'No plotting library and no canvas: an SVG drawn from the contract. The picture is hidden from assistive technology and the numbers are exposed as a real table beside it.',
    ntChartBar: 'A bar is pinned to zero whatever the caller asks for — a truncated bar misstates the ratio it draws.',
    ntSparkline: 'A trend at type size. It goes beside a number, never instead of one.',
    chSessions: 'Sessions', chSignups: 'Sign-ups', chChurn: 'Cancellations',
    chTitle: 'Sessions and sign-ups', chNote: 'Thousands, last seven months',
    chBarTitle: 'Revenue by region', chBarNote: 'Millions of rial',
    chEurope: 'Europe', chAsia: 'Asia', chAmericas: 'Americas',
    // ── Map ───────────────────────────────────────────────────────────
    spMap: 'A located thing', ntMap:
      'The kit ships no tile provider and opens no network — the picture is the product’s. What it owns is the frame, the pins, the projection and the attribution a licence requires.',
    mapTitle: 'Tehran, district 6',
    mapOffice: 'The studio', mapClinic: 'Fatemifar clinic', mapYou: 'You are here',
    mapAttribution: 'Tiles © the product’s own provider',
    // ── Player ────────────────────────────────────────────────────────
    spPlayerAudio: 'Audio', spPlayerVideo: 'Video',
    ntPlayer:
      'Built on the platform’s own element, never instead of it: the decoder, the media keys, picture-in-picture and background playback all come from there. Only the transport is drawn.',
    playerTrack: 'Room tone — studio, take 3',
    playerEpisode: 'Session 04 — the texture pass',
  },
  f: {
    introTitle: 'The tokens are the system.',
    introBody:
      'Components speak only the names below. Swap the style or the colourway and every screen changes at once, because nothing downstream of this contract holds a literal value.',
    colourBody:
      'Roles, never literals. A colourway answers every name below; the style it is paired with answers none of them.',
    surfaces: 'Surfaces', ink: 'Ink', accent: 'Accent', status: 'Status', lines: 'Lines',
    shadowTint: 'Shadow tint',
    shadowTintNote:
      'The colour the style’s offsets are drawn in. Light draws them in the rule colour; dark must use true black, or the offset reads as a glow instead of depth.',
    typeRoles: 'Roles',
    typeNote:
      'The label role is where the two styles diverge most: ledger sets it in mono, uppercase and wide-tracked; vlora sets it in the text face at sentence case. `control` is separate from `label` — a legend printed beside a thing and a thing you press are not the same voice.',
    displayRole: 'Display', displayLgRole: 'Editorial, large', displayXlRole: 'The claim',
    editorialRoles: 'Editorial sizes',
    editorialNote:
      'Above the product ramp: display-lg opens a long document, display-xl is a page’s single claim. Both drop text-wrap: balance — where a claim breaks is a copy decision, so author it with Display.Line. One line may carry the accent, and one may step off the reading margin.',
    titleLarge: 'Title, large', titleMedium: 'Title, medium',
    bodyRole:
      'Body copy carries the substance. It sits at a comfortable measure and never competes with the headings above it.',
    labelRole: 'Label · the style’s signature', controlRole: 'Control · what a button is set in',
    captionRole: 'Caption — secondary, quiet, and never load-bearing.',
    spaceBody: 'A 4px base. Components consume steps, never raw pixels.',
    sizeTitle: 'Fixed sizes',
    sizeBody:
      'Geometry that is neither a space step nor a control height: the diameter of a dot, the side of an avatar, the thickness of a track. These were literals inside components.css until 0.2, where no theme could answer them.',
    radius: 'Radius', radiusNote: 'square under ledger, rounded under vlora',
    elevation: 'Elevation', elevationNote: 'hard offset under ledger, ambient under vlora',
    focusTitle: 'Focus',
    focusBody:
      'One ring, drawn outside the box on the canvas so it reads on any surface, applied to every focusable thing in the kit. Until 0.2 the token was defined by every theme and consumed by a single rule, so tabbing through a nim screen showed nothing.',
    focusHint: 'Press Tab to move through these — the ring is the real one, not a painted copy.',
    focusInvalid: 'An invalid field focuses in danger, so the ring never contradicts the message under it.',
    densityTitle: 'Density',
    densityBody:
      'One multiplier over the control scale and the block padding of anything row-shaped, so a data-dense screen and a mobile flow stay the same system rather than the same components at hand-tuned sizes. It never scales type, and never crosses the 44px touch floor.',
    compact: 'Compact', standard: 'Default', roomy: 'Roomy',
    densityRow: 'Invoice 2291',
    motionCurves: 'Curves',
    motionCurvesNote: 'same distance, same duration — the difference is the curve alone',
    play: 'Play', pause: 'Pause',
    motionDurations: 'Durations',
    durFast: 'Colour, border, press. Anything answering a pointer still on the element.',
    durBase: 'Entrances and exits: sheet, dialog, toast, menu, switch.',
    durSlow: 'Determinate progress only — the one place the viewer watches the value, not the movement.',
    motionAssignment: 'Assignment',
    motionAssignmentBody:
      'One rule decides the curve: something arriving decelerates into place, something the viewer is holding answers on standard, and only two things spring. Exits reverse the entrance at fast, because leaving should never cost the viewer time.',
    motionReduced: 'Reduced motion',
    motionReducedBody:
      'The blanket rule is deliberately not the whole answer. Three of the kit’s animations are not decoration — they are the only signal that something is happening, and stopping them outright leaves a viewer unable to tell a busy interface from a hung one. Reduced motion is a vestibular accommodation, not a request for less information.',
    reducedOn: 'Your system currently requests reduced motion — the curves above are held still, and the three below are what you still get.',
    reducedOff: 'Your system is not requesting reduced motion. Turn it on at the OS level and this page responds immediately.',
    keepsTurning: 'Keeps turning, slower — the spinner is the whole message.',
    keepsFilling: 'Fills instead of sliding: “working, duration unknown”, without movement.',
    goesAway: 'Pure decoration. The grey blocks already say what they need to.',
    press: 'press', hover: 'hover', focusRing: 'focus ring', menuPopover: 'menu · popover',
    dialogSheet: 'dialog · sheet', toastIn: 'toast in', switchThumb: 'switch thumb',
    progressFill: 'progress fill', instant: '0ms — a focus ring never animates in',
  },
  fl: {
    introTitle: 'Flows',
    introBody:
      'The screens a product is judged on before it is used: the intro, the sign-in, the plan picker, the profile, and the bar that carries the whole app. Each is assembled from the kit — no bespoke CSS, and every one answers the style, colourway, scheme and language switches above.',
    // onboarding
    spIntro: 'Three-screen intro',
    ntIntro: 'State is the carousel’s; onDone routes once, from finish or skip.',
    slide1Label: 'Start with one scan', slide1Title: 'Stop guessing\nat your skin',
    slide1Body: 'A short scan makes the signals that matter legible — dryness, texture, glow, and the areas that need care.',
    slide1Proof: 'A clear picture of today', slide1Points: ['Simple scan', 'Plain report', 'No judgement'],
    slide2Label: 'A routine for today', slide2Title: 'Know exactly\nwhat to do tonight',
    slide2Body: 'Instead of scattered advice, only the steps that apply: morning, evening, and the product that suits you.',
    slide2Proof: 'Care, step by step', slide2Points: ['Short routine', 'Ranked needs', 'Daily follow-up'],
    slide3Label: 'Progress you can see', slide3Title: 'Watch your skin\nactually change',
    slide3Body: 'Scans, routines and products stay on one track, so you learn what works for your skin.',
    slide3Proof: 'A trend that holds', slide3Points: ['Skin trend', 'Compare scans', 'Informed choices'],
    next: 'Continue', finish: 'Start my routine', signIn: 'Sign in',
    version: 'Version 0.3.0',
    // auth
    spPhone: 'Phone step', spOtp: 'Code step', spPassword: 'Password step',
    ntPhone: 'Country and national digits are separate props; toE164 joins them.',
    ntOtp: 'One string, not five boxes of state. Paste and SMS autofill take the same path.',
    ntPassword: 'Scoring is the caller’s: a meter that disagrees with the server is worse than none.',
    welcome: 'Welcome', welcomeBody: 'Enter your mobile number.\nWe’ll text a code — no password.',
    phoneLabel: 'Mobile number', sendCode: 'Send code',
    terms: 'By continuing you agree to the terms and the privacy policy.',
    codeTitle: 'Verification code', codeBody: 'Enter the 5-digit code sent to',
    codeLabel: 'Verification code', digit: 'Digit', verify: 'Verify and sign in',
    resendIn: 'Resend available in 42 seconds', back: 'Back',
    passwordTitle: 'Sign in with a password', passwordBody: 'Use the email and password on your account.',
    emailLabel: 'Email', passwordLabel: 'Password', forgot: 'Forgotten your password?',
    signInAction: 'Sign in', useCode: 'Sign in with a code instead',
    // plans
    spPlans: 'Plan picker', spBilling: 'Billing period',
    ntPlans: 'The whole card is the control, and the price is a node — currency and digits are the product’s locale decision.',
    free: 'Free', plus: 'Plus', pro: 'Pro',
    freeTag: 'A sensible start', plusTag: 'AI, working on your skin', proTag: 'Everything, at full capacity',
    recommended: 'Recommended', mostCapacity: 'Most capacity',
    perPack: 'This package', perMonth: 'Per month', soon: 'Soon',
    fFree1: '3 simple scans a month', fFree2: 'Basic skin report', fFree3: 'One week of scan history',
    fFree4: 'Personalised routine', fFree5: 'Advanced AI analysis',
    fPlus1: 'Unlimited simple scans', fPlus2: '4 advanced scans a month', fPlus3: 'Personalised routine',
    fPlus4: 'Product recommendations', fPlus5: 'Specialist review',
    oneMonth: '1 month', threeMonths: '3 months', sixMonths: '6 months', save: 'Save 15%',
    // profile
    spProfile: 'Profile header', ntProfile: 'A header, not a dashboard — anything needing a chart goes below it.',
    account: 'vlora account', person: 'Sara Ahmadi',
    completion: 'Profile complete', scans: 'Scans', streak: 'Day streak',
    skinChip: 'Combination skin', planChip: 'Plus · 6 months',
    completeProfile: 'Complete skin profile', seeAnalysis: 'See skin analysis',
    // tab bar
    // sign-in flow
    spSignIn: 'The whole sign-in',
    ntSignInFlow:
      'Mounted, not composed: the step machine, the resend countdown and the error states are the component’s. This demo accepts 12345.',
    wrongCode: 'That code is not right. Check it and try again.',
    signInCopy: {
      back: 'Back',
      codeLabel: 'Verification code',
      codeSubtitle: (destination: string) => `Enter the 5-digit code sent to ${destination}`,
      codeTitle: 'Verification code',
      identifierLabel: 'Email',
      passwordLabel: 'Password',
      passwordSubtitle: 'Use the email and password on your account.',
      passwordTitle: 'Sign in with a password',
      phoneLabel: 'Mobile number',
      phoneSubtitle: 'Enter your mobile number. We’ll text a code — no password.',
      phoneTitle: 'Welcome',
      resend: 'Send the code again',
      resendIn: (seconds: number) => `You can ask for a new code in ${seconds}s`,
      sendCode: 'Send code',
      signIn: 'Sign in',
      usePassword: 'Sign in with a password instead',
      usePhone: 'Sign in with a code instead',
      verify: 'Verify and sign in',
    },
    // chat
    spChat: 'Text, voice, video, file',
    ntChat:
      'Media plays in the platform’s own elements. The composer records voice where the browser allows it, and hands the caller both the object URLs and the Files.',
    chatPresence: 'Online',
    chatPlaceholder: 'Write a message',
    chat1: 'Morning — did the new evening routine arrive?',
    chat2: 'It did. Starting tonight, and I’ll send a scan on Friday.',
    chat3: 'Two seconds of the texture on my cheek.',
    chat4: 'Notes from the last session are attached.',
    chatLabels: {
      deleted: 'Message deleted',
      download: 'Download',
      edited: 'edited',
      failed: 'Not delivered',
      more: 'Message actions',
      pause: 'Pause',
      play: 'Play',
      react: 'Add a reaction',
      read: 'Read',
      reply: 'Reply',
      sending: 'Sending',
      sent: 'Sent',
      today: 'Today',
      typing: 'is typing',
      yesterday: 'Yesterday',
      voiceMessage: 'Voice message',
    },
    composerLabels: {
      attach: 'Attach a file',
      cancel: 'Cancel recording',
      cancelReply: 'Cancel reply',
      discard: 'Remove attachment',
      record: 'Record a voice message',
      recording: 'Recording',
      replyingTo: 'Replying to',
      send: 'Send',
      stop: 'Stop and attach',
      video: 'Attach a video',
    },
    // plans, profile, shell
    ntPlanPicker:
      'Holds the selection, keeps the cycle and the prices in step, and hands onSubmit the pair a checkout needs.',
    continueToPayment: 'Continue to payment',
    planNote: 'The final amount is shown before payment.',
    ntProfileScreen: 'Rows are data — a label, an icon, and either somewhere to go or something to toggle.',
    groupAccount: 'Account', groupPreferences: 'Preferences', groupApp: 'App',
    rowPersonal: 'Personal details', rowSkin: 'Skin profile', rowPlan: 'Subscription',
    rowNotifications: 'Notifications', rowNotificationsSub: 'Daily at 08:00',
    rowReduced: 'Reduced motion', rowVersion: 'Version', rowDelete: 'Delete account',
    signOut: 'Sign out',
    ntAppShell: 'One scroll region, and content that reserves the room the bar floats over. Past 64rem the same shell widens and the tab bar becomes a side rail — this specimen pins the phone frame because the demo box is phone-sized.',
    shellBody: 'The page scrolls here. The bar floats above the safe area, and the content it covers is padded for, not hidden.',
    // wizard
    spWizard: 'One question per screen',
    ntWizard:
      'The step index is the wizard’s; the answers are not. Each step reports only whether it can continue.',
    wizardQ1: 'How was today?', wizardS1: 'One tap. You can change it later.',
    wizardQ2: 'What shaped it?', wizardS2: 'Pick up to three.',
    wizardQ3: 'Anything worth remembering?', wizardS3: 'A line is enough.',
    moodBad: 'Rough', moodLow: 'Low', moodOk: 'Fine', moodGood: 'Good', moodGreat: 'Great',
    causeWork: 'Work', causeFamily: 'Family', causeSleep: 'Sleep', causeHealth: 'Health',
    causeFriends: 'Friends', causeOutdoors: 'Outdoors',
    notePlaceholder: 'Today I noticed…', wizardDone: 'Save entry',
    // checkout
    spCheckout: 'Order summary and payment',
    ntCheckout:
      'Every figure is a node the caller formatted. Money is the last thing a UI kit should be rounding.',
    payWith: 'Payment method', gatewayCard: 'Bank card', gatewayCardDesc: 'Pay online, confirmed instantly',
    gatewayTransfer: 'Bank transfer', gatewayTransferDesc: 'Send a receipt for review',
    gatewayReview: 'Manual review', gatewayDefault: 'Fastest',
    gatewayDetail: 'IR62 0170 0000 0011 2345 6789',
    orderTitle: 'What you are buying',
    linePlan: 'Plus subscription', linePlanMeta: '6 months · renews 1405/12/01',
    lineScan: 'Advanced scan credits', lineScanMeta: '4 credits',
    subtotal: 'Subtotal', tax: 'Tax (9%)', fee: 'Gateway fee', totalLabel: 'Total',
    payNow: 'Pay now', payNote: 'The final amount is shown by the gateway before you confirm.',
    // task progress
    spProgress: 'A job with named stages',
    ntProgress:
      'The stages are the point: a percentage says how long to wait, a named stage says which part failed.',
    scanTitle: 'Analysing your scan', scanCaption: 'This usually takes under a minute.',
    stepUpload: 'Uploading the photo', stepQuality: 'Checking framing and light',
    stepAnalyse: 'Reading skin signals', stepRoutine: 'Building your routine',
    stepReport: 'Writing the report',
    stepFailedDetail: 'Too dark to read the cheek area — retake in daylight.',
    cancelJob: 'Cancel', stepsOf: (done: number, total: number) => `${done} of ${total} stages`,
    stepStatus: {
      active: 'Working on it',
      done: 'Done',
      failed: 'Failed',
      pending: 'Waiting',
      skipped: 'Skipped',
    },
    // console layer
    spConsole: 'Page, panel, metric, facts', spConsoleTable: 'Data table',
    ntConsole:
      'The pieces below the shell. Every console had grown its own page container, titled section, counter row and label/value block; these are those, on the token contract, so two consoles agree on a measurement.',
    ntConsoleTable:
      'One component resolves the four states a remote collection is ever in — error, first load, empty, rows — in that order. Every hand-rolled version got the order wrong.',
    csRequests: 'Requests', csErrors: 'Error rate', csLatency: 'p95 latency', csQueue: 'Queue depth',
    csFleet: 'Fleet posture', csSince: 'vs. yesterday', csDeploy: 'Deploy log',
    csHost: 'Host', csRegion: 'Region', csImage: 'Image', csUptime: 'Uptime',
    csHealthy: 'Healthy', csDegraded: 'Degraded', csDraining: 'Draining',
    csNode: 'Node', csState: 'State', csTasks: 'Tasks', csEmpty: 'No nodes reported',
    csEmptyBody: 'The selected cluster returned an empty inventory.',
    spBrand: 'Brand lockup and vendor marks',
    ntBrand:
      "Every console in the family had written the same flex row, mark box, name and tagline — and the copies disagreed on the gap, the tagline colour and whether the name was a title or a body run. `Brand` is that object once; `nameAccent` takes the product's own colour through one custom property, so a two-tone wordmark costs a variable rather than a literal. `BrandMark` is a separate registry from `Icon` on purpose: a role icon must mean one thing across every screen, a vendor mark means one product.",
    brandTagline: 'Remote Docker Swarm control plane',
    spProcedure: 'Stage track, rail, copy chip',
    ntProcedure:
      'A console procedure spread over five sections: the stages it walks, the numbered panels that collect each decision, and the sticky rail where the whole plan is read back and committed. The rail is the only place the action is issued from.',
    prStages: 'Provider', prStages2: 'Repository', prStages3: 'Discover', prStages4: 'Review', prStages5: 'Deploy',
    prConnect: 'Connect source', prSelect: 'Select and verify', prScan: 'Scans and evidence',
    prClassify: 'Classify and map', prConfigure: 'Configure and deploy',
    prPlan: 'Deployment plan', prApps: 'Applications', prImages: 'Images (immutable)',
    prWarnings: 'Warnings', prBlockers: 'Blockers', prDeploy: 'Deploy',
    prBlocked: 'Resolve blockers to enable deployment',
    prWarning: "Compose file uses 'latest' tag in /services/worker",
    prBlocker: "Service 'worker' is missing a healthcheck",
    prProviderBody: 'A verified connection reads as a record; the form returns only when there is something to add or replace.',
    // admin
    spAdmin: 'Console layout', spDetail: 'Record header', spFilters: 'Active filters', spFeed: 'Activity',
    ntAdmin:
      'The counterpart to AppShell, not a variant of it: two columns, a deep hierarchy, and the same sidebar becoming a drawer below the breakpoint.',
    ntDetail: 'Actions sit at the top, where an operator working a queue acts without reading the whole record.',
    ntFeed: 'Absolute timestamps: an audit trail is read to reconstruct a sequence.',
    navOverview: 'Overview', navCommerce: 'Commerce', navMonitoring: 'Monitoring',
    navDashboard: 'Dashboard', navUsers: 'Users', navOrders: 'Orders', navPayments: 'Payments',
    navQueues: 'Queues', navScans: 'Scans', navSettings: 'Settings',
    adminSession: 'Session live', adminBuild: 'Build 0.6.0',
    paymentTitle: 'Payment #48210', paymentSubtitle: 'Manual receipt · Plus, 6 months',
    paymentMeta: 'Last updated 23 Aug, 09:41', paymentStatus: 'Awaiting review',
    approve: 'Approve', reject: 'Reject', backToPayments: 'Payments',
    filterStatus: 'Status', filterPending: 'Pending', filterGateway: 'Gateway',
    filterManual: 'Manual receipt', filterRange: 'Range', filterThisWeek: 'This week',
    clearAll: 'Clear all',
    feed1: 'approved payment', feed2: 'rejected receipt', feed3: 'changed the plan of',
    feed4: 'opened a support thread with',
    actorNima: 'Nima', actorSara: 'Sara', targetPayment: '#48210', targetUser: 'user 3391',
    spTabBar: 'Bottom navigation', ntTabBar: 'Routing stays outside: renderItem hands the caller the props for their own Link.',
    tabHome: 'Home', tabRoutine: 'Routine', tabScan: 'Scan', tabReflect: 'Reflect', tabProfile: 'Profile',
    // ── Messenger: channels, groups, direct ───────────────────────────
    spMessenger: 'Channels, groups, direct',
    ntMessenger:
      'Two panes on a wide box, one on a narrow one — and the switch is a container query, because a messenger is usually embedded in something.',
    mgChannels: 'Channels', mgGroups: 'Groups', mgDirect: 'Direct',
    mgSearch: 'Search conversations',
    mgCompose: 'New conversation',
    mgMembersWord: 'members',
    roomShip: 'ship-room', roomDesign: 'design-review', roomIncidents: 'incidents',
    groupClinic: 'Clinic team', groupLaunch: 'Launch crew',
    personAmir: 'Amir Tehrani', personLeila: 'Leila Roshan',
    mgOnline: 'Sara, Amir and 4 others',
    mgPreviewShip: 'Amir: tagging 0.9 tonight',
    mgPreviewDesign: 'Leila: the tail only on the last bubble',
    mgPreviewIncidents: 'Resolved — edge-2.fra back in rotation',
    mgPreviewClinic: 'You: notes are attached',
    mgPreviewLaunch: 'Leila: map looks right now',
    mgPreviewSara: 'Voice message · 0:03',
    mgPreviewAmir: 'Typing…',
    // ── Group transcript ──────────────────────────────────────────────
    spGroup: 'A group, with everything a message can do',
    ntGroup:
      'Consecutive messages from one person are a run: one avatar, one name, one timestamp, and a tail on the last bubble only.',
    gm1: 'Pulled the transcript apart this morning. Runs are the whole difference — four bubbles from one person should read as one turn.',
    gm2: 'Agreed. And the tail only on the last one.',
    gm3: 'Traffic for the week, since someone will ask in standup:',
    gm4: 'That dip on Thursday is the deploy, not a regression.',
    gm5: 'Meeting point for Friday — the clinic entrance, not the main gate.',
    gm6: 'Noted. I’ll be there at nine.',
    gm7: 'Here’s the room tone from the studio.',
    gm8: 'This one I sent by mistake.',
    gmSystem: 'Leila added Amir to the group',
    gmChartTitle: 'Sessions this week',
    gmChartNote: 'Thousands, all regions',
    gmMapTitle: 'Clinic entrance',
    gmMapAttribution: 'Tiles © the product’s own provider',
    acReply: 'Reply', acCopy: 'Copy text', acForward: 'Forward', acPin: 'Pin', acDelete: 'Delete',
    // ── Assistant ─────────────────────────────────────────────────────
    spAssistant: 'An assistant thread',
    ntAssistant:
      'Not bubbles: an answer is a document, and a document does not go in a bubble. Only the viewer’s own turn keeps a surface.',
    asName: 'nim assistant',
    asPlaceholder: 'Ask anything',
    asQ1: 'Why is our p99 up since Tuesday?',
    asA1Lead: 'Two things happened on Tuesday, and only one of them is yours.',
    asA1Body:
      'The 09:40 deploy moved image resizing onto the request path, which added about 40ms at the median and considerably more at the tail. Separately, edge-2.fra dropped out of rotation for three hours that afternoon, so the remaining node in that region took the whole load.',
    asA1Tail: 'The deploy is the one to act on. The node is already back.',
    asStep1: 'Read deploy log', asStep2: 'Queried latency by region', asStep3: 'Compared to last week',
    asStepDetail: '2 regions · 14 days',
    asSource1: 'Deploy 4821 — release notes',
    asSource2: 'p99 by region, 14 days',
    asEmptyTitle: 'Ask about the system',
    asEmptyBody: 'It reads the deploy log, the metrics and the incident record, and says which of them explains what you asked.',

  },
  clients: ['Atelier Fatemifar', 'Iranian Law Club', 'Reelforge', 'Vlora', 'Nim Studio'],
}

const fa: typeof en = {
  dir: 'rtl' as const,
  locale: 'fa-IR',
  tagline: 'سامانهٔ طراحی و کیت رابط کاربری',
  bylinePrefix: 'طراحی و ساخت',
  author: 'نیما سارایان',
  pages: { components: 'کامپوننت‌ها', flows: 'جریان‌ها', foundations: 'مبانی' },
  controls: { colorway: 'پالت رنگ', language: 'زبان', page: 'صفحه', scheme: 'طرح رنگ', style: 'سبک' },
  schemes: { dark: 'تیره', light: 'روشن', system: 'سیستم' },
  nav: {
    badge: 'نشان', button: 'دکمه', card: 'کارت', color: 'رنگ', composition: 'ترکیب‌بندی',
    data: 'داده', density: 'تراکم', feedback: 'بازخورد', focus: 'فوکوس', form: 'کنترل‌های فرم',
    input: 'ورودی', list: 'فهرست', admin: 'پنل مدیریت', auth: 'ورود', chat: 'گفت‌وگو', console: 'لایهٔ کنسول',
    checkout: 'پرداخت', onboarding: 'شروع آشنایی', progress: 'کارهای طولانی', wizard: 'ویزارد',
    plans: 'اشتراک‌ها', profile: 'پروفایل', tabbar: 'نوار پایین',
    motion: 'حرکت', navigation: 'ناوبری', overlay: 'لایه‌ها', shape: 'شکل و ارتفاع',
    sheet: 'شیت', space: 'فاصله', stat: 'آمار', type: 'تایپوگرافی',
    chart: 'نمودارها', map: 'نقشه‌ها', player: 'پخش‌کننده',
    messenger: 'مسنجر', assistant: 'دستیار',
    diagnosis: 'تشخیص',
    evidence: 'شواهد',
  },
  t: {
    spProvenance: 'عددی که می‌گوید از کجا آمده',
    spUnknownEmpty: 'چیزی اینجا نیست، و نمی‌توان دید',
    ntProvenance: 'اعداد یک کنسول به‌عنوان واقعیت خوانده می‌شوند؛ پس آن‌ها که از ابزاری آمده‌اند می‌گویند از کجا، و آن‌ها که نیامده‌اند با نگفتنش آشکار می‌شوند.',
    ntUnknownEmpty: 'دو ادعای متفاوت که بیشتر کنسول‌ها یکسان نمایش می‌دهند. خوشه‌ای بدون استک، استکی ندارد؛ خوشه‌ای که عاملش پاسخ نداده، شمار استک‌هایش نامعلوم است.',
    evNotMeasured: 'اندازه‌گیری نشده',
    evEmptyTitle: 'بدون استک', evEmptyBody: 'این سوارم هیچ استکی زمان‌بندی نکرده است. مدیر پاسخ داد.',
    evUnknownTitle: 'استک‌ها دیده نمی‌شوند', evUnknownBody: 'هیچ مدیری پاسخ نداد، پس شمار استک‌ها نامعلوم است نه صفر.',
    spLedger: 'اندازه‌گیری‌شده، و آنچه شاهد نیست',
    spTrail: 'آنچه یک نتیجه بر آن تکیه داشت',
    ntLedgerHonest: 'بیشتر کنسول‌ها هر دو نیمه را در یک شبکه می‌گذارند و همین خواننده را به میانگین‌گیری میان آن‌ها دعوت می‌کند — و نبودی که در یک عدد میانگین گرفته شود، همان‌جایی است که داشبورد عددی را گزارش می‌کند که کسی اندازه نگرفته است.',
    ntTrailAge: 'کهنگی، جوهر ماجراست نه فراداده. نتیجه‌ای که از خوانشی پنج‌دقیقه‌ای گرفته شود، حدسی است در جامهٔ واقعیت.',
    evMeasured: 'اندازه‌گیری‌شده', evAbsent: 'شاهد نیست',
    evNodes: 'گره‌های آماده', evTasks: 'پوشش وظایف', evMemory: 'حافظهٔ مصرفی',
    evCpu: 'بهره‌وری پردازنده', evTraces: 'ردیابی‌ها',
    evSwarm: 'مدیر خوشه', evProbe: 'کاوشگرهای فقط‌خواندنی میزبان',
    evWhyCpu: 'بار متوسط، بهره‌وری نیست', evWhyTraces: 'هیچ گردآورنده‌ای نصب نشده',
    evCoverage: '۴/۴ کاوشگر سالم',
    evTrailCaption: 'هر اندازه‌گیری که این زنجیره از آن استفاده کرد، همراه با زمان ثبتش.',
    spCausalChain: 'زنجیره‌ای که استدلالش را نشان می‌دهد',
    spCaveat: 'آنچه دانسته نیست',
    spDiff: 'آنچه تغییر کرده',
    ntCausalStops: 'هر حلقه اندازه‌گیری پشت خود را همراه دارد. حلقه‌ای بدون شاهد، عمداً کم‌رنگ‌تر کشیده می‌شود — گامی بی‌شاهد همان چیزی است که خواننده باید به آن شک کند و مؤلفه نباید آن را بپوشاند.',
    ntCaveatQuiet: 'هاشور، نه پس‌زمینهٔ رنگی: در حالت خاکستری، در چاپ و در تصویری که در کانال رخداد جای‌گذاری می‌شود باقی می‌ماند. هشدار نیست — می‌گوید اندازه‌گیری‌نشده، نه نادرست.',
    ntDiffMarkers: 'علامت‌های + و − متن‌اند، نه فقط رنگ. تمایزی که تنها بر قرمز و سبز تکیه کند برای حدود یک نفر از هر دوازده مرد کار نمی‌کند.',
    dgObserved: 'مشاهده', dgBecause: 'زیرا',
    dgClaim1: 'سرویس api-gateway ۲ از ۳ وظیفهٔ خواسته‌شده را اجرا می‌کند.',
    dgClaim2: 'وظیفهٔ سوم ۶ دقیقه در انتظار مانده است؛ پس مسئله جای‌گذاری است، نه کرش.',
    dgClaim3: 'روی worker-03 تنها ۱٫۴ گیگابایت آزاد است و ایمیج به ۲٫۱ گیگابایت نیاز دارد.',
    dgEv1: '۲/۳ وظیفه', dgEv2: 'بدون رخداد راه‌اندازی مجدد', dgEv3: '۱٫۴ آزاد · ۲٫۱ لازم',
    dgSrc1: 'مدیر سوارم · ۴ ثانیه پیش', dgSrc2: 'تاریخچهٔ وظیفه · ۴ ثانیه پیش', dgSrc3: 'کاوشگر میزبان · ۲۲ ثانیه پیش',
    dgFix: 'با هرس ۱۱ ایمیج بلااستفاده، ۳٫۲ گیگابایت آزاد کنید.',
    dgCaveatTitle: 'آنچه این تشخیص نمی‌بیند',
    dgCaveatBody: 'کشیدن ایمیج ممکن است به دلیل احراز هویت رجیستری هم شکست بخورد، که بدون تلاش برای آن قابل آزمودن نیست.',
    introTitle: 'کامپوننت‌ها',
    introBody:
      'همهٔ گونه‌ها، اندازه‌ها و حالت‌هایی که کیت ارائه می‌کند. سبک، پالت رنگ، طرح رنگ یا زبان را از نوار بالا عوض کنید و دوباره این صفحه را بخوانید — هیچ‌چیز در ادامه برای هر ترکیب از نو نوشته نشده است.',
    saveChanges: 'ذخیرهٔ تغییرات', startScan: 'شروع اسکن', cancel: 'انصراف', skip: 'رد کردن',
    del: 'حذف', small: 'کوچک', medium: 'متوسط', large: 'بزرگ', saving: 'در حال ذخیره',
    unavailable: 'در دسترس نیست', newEntry: 'ورودی تازه', continueLabel: 'ادامه',
    search: 'جست‌وجو', settings: 'تنظیمات', add: 'افزودن',
    neutral: 'خنثی', accent: 'تأکید', live: 'زنده', pending: 'در انتظار', failed: 'ناموفق',
    info: 'اطلاع', beta: 'آزمایشی',
    cardDefault: 'پیش‌فرض', cardRaised: 'برجسته', cardMuted: 'کم‌رنگ', cardAccent: 'تأکیدی',
    cardDefaultBody: 'یک صفحهٔ خط‌کشی‌شده روی بوم.',
    cardRaisedBody: 'ارتفاع سبک جاری را حمل می‌کند.',
    cardMutedBody: 'پشت همسایه‌هایش عقب می‌نشیند.',
    cardAccentBody: 'برای یک مورد برجستهٔ واحد.',
    viewReport: 'دیدن گزارش', session: 'جلسهٔ ۰۴', complete: 'کامل',
    cardBody: 'ترکیب‌بندی کارِ کارت است؛ فاصلهٔ میان کارت‌ها به صفحه تعلق دارد.',
    eventsPerMinute: 'رویداد در دقیقه', latency: 'تأخیر p99', throughput: 'افزایش توان عبوری',
    costReduction: 'کاهش هزینه',
    email: 'رایانامه', emailHint: 'فقط برای فرستادن گزارش از آن استفاده می‌کنیم.',
    findRoutine: 'یافتن یک روتین', fullName: 'نام و نام خانوادگی', fullNameError: 'این فیلد الزامی است.',
    workspace: 'فضای کاری', notes: 'یادداشت‌ها', notesHint: 'مارک‌داون پشتیبانی می‌شود.',
    notesPlaceholder: 'چه چیزی تغییر کرد؟', cadence: 'تناوب', daily: 'روزانه', weekly: 'هفتگی',
    monthly: 'ماهانه', chooseOne: 'یکی را انتخاب کنید', weeklySummary: 'خلاصهٔ هفتگی',
    weeklySummaryDesc: 'هر دوشنبه صبح فرستاده می‌شود.', notOnPlan: 'در این طرح در دسترس نیست',
    reducedMotion: 'کاهش حرکت', reducedMotionDesc: 'فقط روی همین دستگاه اعمال می‌شود.',
    load: 'بار', range: 'بازه', week: 'هفته', month: 'ماه', year: 'سال',
    spRadio: 'گروه رادیویی', ntRadio: 'یک fieldset با legend واقعی — پرسش باید پیش از پاسخ‌ها خوانده شود.',
    rgDelivery: 'ارسال', rgStandard: 'عادی', rgStandardDesc: 'سه تا پنج روز کاری.',
    rgExpress: 'سریع', rgExpressDesc: 'روز کاری بعد، پیش از ظهر.',
    rgPickup: 'دریافت حضوری', rgHint: 'تا پیش از ارسال سفارش قابل تغییر است.',
    spChips: 'تراشه‌ها و ورودی برچسبی', ntChips: 'تراشه یک شیء است که می‌توان انداختش؛ نشان برچسبی است دربارهٔ آن.',
    chipRecipients: 'گیرندگان', chipHint: 'اینتر یا ویرگول ثبت می‌کند؛ backspace آخری را برمی‌دارد.',
    chipAdd: 'افزودن نشانی', chipRemove: 'حذف', chipFilters: 'پالایه‌ها', chipUnread: 'خوانده‌نشده', chipFlagged: 'نشان‌دار',
    chipArchived: 'بایگانی', chipOverdue: 'سررسیده',
    spRating: 'امتیاز', ntRating: 'رادیوها پشت ستاره‌ها، تا کلیدهای جهت و ارسال فرم از خودِ پلتفرم بیاید.',
    ratingLabel: 'به این جلسه امتیاز بدهید', ratingStatic: 'میانگین ۱۲۸ امتیاز',
    spUpload: 'انداختن فایل', ntUpload: 'ناحیه یک label دور ورودی فایل واقعی است؛ خودِ بارگذاری کارِ محصول می‌ماند.',
    uploadLabel: 'رسید را اینجا بیندازید', uploadPrompt: 'یا برای انتخاب فایل کلیک کنید',
    uploadCaption: 'PNG، JPG یا PDF · تا ۱۰ مگابایت', uploadPicked: 'انتخاب‌شده',
    spAccordion: 'بازشونده', ntAccordion: 'پنل تا اندازهٔ محتوای خودش باز می‌شود — یک ردیف گرید، نه max-height اندازه‌گیری‌شده.',
    accBilling: 'صورت‌حساب', accBillingBody: 'فاکتورها اول هر ماه صادر و از کارت ثبت‌شده تسویه می‌شوند.',
    accSecurity: 'امنیت', accSecurityBody: 'ورود دومرحله‌ای برای همهٔ اعضای فضای کاری اعمال می‌شود.',
    accData: 'برون‌بری داده', accDataBody: 'برون‌بری در پس‌زمینه آماده می‌شود و هفت روز در دسترس می‌ماند.',
    accItems: '۳ بخش',
    spTimeline: 'خط زمان', ntTimeline: 'یک فهرست مرتب: ادعای خط زمان همان ترتیب است.',
    tlSubmitted: 'رسید ثبت شد', tlSubmittedAt: '۱ شهریور، ۰۹:۱۲',
    tlReview: 'برای بررسی برداشته شد', tlReviewAt: '۱ شهریور، ۰۹:۴۱',
    tlApproved: 'تأیید شد', tlApprovedAt: '۱ شهریور، ۱۰:۰۲',
    tlSettled: 'به کیف پول تسویه شد', tlSettledAt: 'در انتظار',
    tlReviewBody: 'به صف پرداخت‌ها واگذار شد.',
    spDataList: 'فهرست داده', ntDataList: 'فهرست توصیفی، چون این برچسب‌ها این مقادیر را توصیف می‌کنند — نه جدولی که وانمود می‌کند شبکه است.',
    dlPlan: 'طرح', dlPlanValue: 'پلاس · صورت‌حساب سالانه', dlSeats: 'صندلی', dlSeatsValue: '۱۲ از ۲۰ استفاده‌شده',
    dlRenews: 'تمدید', dlRenewsValue: '۱۰ اسفند ۱۴۰۵', dlReference: 'شناسه',
    profileSub: 'وارد شده · nimax.sr@gmail.com', notifications: 'اعلان‌ها',
    notificationsSub: 'روزانه ساعت ۰۸:۰۰', appearance: 'ظاهر', signOut: 'خروج',
    openedProfile: 'نمایه باز شد', openedNotifications: 'اعلان‌ها باز شد',
    signedOut: 'خارج شدید',
    scanQueued: 'اسکن در صف', scanQueuedBody: 'نتیجه معمولاً ظرف یک دقیقه می‌رسد.',
    newRelease: 'تازه در این نسخه',
    newReleaseBody: 'روتین‌ها را حالا می‌توان با پزشک‌تان به اشتراک گذاشت.',
    profileCurrent: 'نمایهٔ شما به‌روز است.', connectionSlow: 'اتصال کند است',
    connectionSlowBody: 'در پس‌زمینه تلاش را ادامه می‌دهیم.',
    uploadFailed: 'بارگذاری ناموفق بود', uploadFailedBody: 'حجم فایل از ۱۲ مگابایت بیشتر بود.',
    upload: 'بارگذاری', working: 'در حال کار', successToast: 'اعلان موفقیت',
    changesSaved: 'تغییرات ذخیره شد.', withAction: 'همراه با کنش', undo: 'واگرد',
    entryDeleted: 'ورودی حذف شد.', addFirstRoutine: 'نخستین روتین‌تان را بیفزایید',
    noRoutines: 'هنوز روتینی نیست',
    noRoutinesBody:
      'هنوز چیزی ثبت نشده است. به‌محض افزودن یک روتین، همراه با تاریخچه‌اش همین‌جا نمایان می‌شود.',
    openSheet: 'باز کردن شیت', confirmRoutine: 'تأیید روتین', confirm: 'تأیید',
    sheetBody:
      'شیت، سطح مودالِ کیت است. صفحهٔ پشتش را قفل می‌کند، با Escape بسته می‌شود و فوکوس را به همان چیزی که بازش کرده برمی‌گرداند.',
    name: 'نام', eveningRoutine: 'روتین شبانه', remindMe: 'یادآوری کن',
    workspaceCrumb: 'فضای کاری', billing: 'صورت‌حساب', invoices: 'فاکتورها',
    open: 'باز', overdue: 'سررسید گذشته', paid: 'پرداخت‌شده',
    pageSummary: (page: number) =>
      `صفحهٔ ${new Intl.NumberFormat('fa-IR').format(page)} از ۱۴ · ۸۴ فاکتور`,
    invoiceActions: 'عملیات فاکتور', thisInvoice: 'همین فاکتور', downloadPdf: 'دریافت پی‌دی‌اف',
    sendToClient: 'ارسال برای مشتری', duplicate: 'تکثیر', voidInvoice: 'ابطال فاکتور',
    voidTitle: 'این فاکتور ابطال شود؟', voidDesc: 'فاکتور ۲۲۹۱ · آتلیه فاطمی‌فر · ۴٬۲۰۰ یورو',
    voidBody:
      'ابطال، فاکتور را با ماندهٔ صفر در دفتر نگه می‌دارد و به مشتری اطلاع می‌دهد. این کار برگشت‌پذیر نیست — اگر کار تحویل شده، به‌جای ابطال یادداشت بستانکار صادر کنید.',
    keepIt: 'نگه‌داشتن', adjustDue: 'تنظیم تاریخ سررسید', dueDate: 'تاریخ سررسید', apply: 'اعمال',
    reconcile: 'مغایرت‌گیری با بانک', archiveTip: 'بایگانی — قابل جست‌وجو می‌ماند',
    archive: 'بایگانی',
    client: 'مشتری', reference: 'شناسه', status: 'وضعیت', amount: 'مبلغ',
    quantity: 'تعداد', startTyping: 'نام مشتری را بنویسید',
    noMatch: (query: string) => `مشتری‌ای با «${query}» پیدا نشد. ایجادش کنید.`,
    today: 'امروز', all: 'همه',
    compositionDesc: 'هرچه در ادامه می‌بینید خروجی کیت است — صفحه فقط ریتم را تأمین می‌کند.',
    yourMorning: 'صبح شما', streak: 'روزهای پیاپی', days: 'روز', adherence: 'پایبندی',
    nextCheck: 'بررسی بعدی', onTrack: 'طبق برنامه', steps: '۳ مرحله',
    routineBody: 'شوینده، سرم و ضدآفتاب — بعد از هر اسکن خودکار ثبت می‌شود.',
    completion: 'پیشرفت',
    spAScreenAssembledFromTheKit: 'صفحه\u200cای ساخته\u200cشده از خود کیت',
    spBanners: 'بنرها',
    spBottomSheet: 'شیت پایینی',
    spBreadcrumb: 'مسیر راهنما',
    spChoice: 'انتخاب',
    spCombobox: 'کمبوباکس',
    spDateField: 'فیلد تاریخ',
    spDatePicker: 'انتخابگر تاریخ',
    spCalendarSystem: 'گاه‌شماری',
    ntJalali:
      'ماه‌های جلالی، ارقام فارسی، هفته‌ای که شنبه آغاز می‌شود — و مقداری که برگردانده می‌شود همچنان تاریخ میلادی ISO است.',
    ntPickerCompact:
      'شکل فشرده: یک فیلد، جدول پشت یک دکمه، و گاه‌شماری دیگر زیر آن.',
    calGregorian: 'میلادی', calJalali: 'جلالی', hearingDate: 'تاریخ جلسه',
    spCommandPalette: 'پالت فرمان',
    spDialog: 'دیالوگ',
    spEmptyState: 'حالت خالی',
    spIconButton: 'دکمهٔ آیکونی',
    spLoading: 'در حال بارگذاری',
    spMenu: 'منو',
    spMetrics: 'سنجه\u200cها',
    spPagination: 'صفحه\u200cبندی',
    spPopover: 'پاپ\u200cاوور',
    spProgressSkeleton: 'پیشرفت و اسکلت',
    spRows: 'ردیف\u200cها',
    spSegmented: 'کنترل بخش\u200cبندی\u200cشده',
    spSizes: 'اندازه\u200cها',
    spSlider: 'اسلایدر',
    spStepper: 'استپر',
    spTable: 'جدول',
    spTabs: 'تب\u200cها',
    spTextInputs: 'ورودی\u200cهای متنی',
    spToast: 'توست',
    spTones: 'تن\u200cها',
    spTooltip: 'تول\u200cتیپ',
    spVariants: 'گونه\u200cها',
    spStatesIcons: 'حالت\u200cها و آیکون\u200cها',
    spWithHeaderAndFooter: 'با سربرگ و پابرگ',
    ntAMenuSGeometry: 'هندسهٔ منو با محتوای یک فرم',
    ntARealDialogTop: 'یک <dialog> واقعی — لایهٔ رویین و تلهٔ فوکوس از خودِ پلتفرم',
    ntPaletteRanks: 'بر پایهٔ جای تطبیق رتبه می\u200cدهد · ↑↓ · Enter اجرا می\u200cکند · کلید ⌘K که بازش می\u200cکند از آنِ برنامه است',
    palOpenIt: 'باز کردن پالت',
    palFindOrRun: 'یافتن یک صفحه یا اجرای یک کنش',
    palSearch: 'جست\u200cوجوی صفحه\u200cها و کنش\u200cها…',
    palGoTo: 'رفتن به',
    palRun: 'اجرا',
    palInvoices: 'فاکتورها',
    palInvoicesHint: 'هرچه صادر شده، به تفکیک مشتری و وضعیت',
    palClients: 'مشتریان',
    palClientsHint: 'مخاطبان صورتحساب، شرایط و مانده\u200cها',
    ntASevenSlotWindow: 'پنجره\u200cای هفت\u200cخانه که عرضش هرگز تغییر نمی\u200cکند',
    ntArrowKeysEscapeFocus: 'کلیدهای جهت\u200cدار · Escape · بازگشت فوکوس',
    ntHoverWaits200msFocus: 'هاور ۲۰۰ میلی\u200cثانیه صبر می\u200cکند · فوکوس نه',
    ntLoadingKeepsTheLabel: 'حالت بارگذاری برچسب را سر جایش نگه می\u200cدارد تا عرض نپرد',
    ntNoBespokeCss: 'بدون هیچ CSS سفارشی',
    ntRowHeightFollowsNim: 'ارتفاع ردیف از --nim-density پیروی می\u200cکند',
    ntScrollLockEscapeFocus: 'قفل اسکرول · Escape · بازگشت فوکوس',
    ntSwitchesARegionA: 'یک ناحیه را عوض می\u200cکند — کنترل بخش\u200cبندی\u200cشده یک مقدار را تنظیم می\u200cکند',
    ntTheLastCrumbIs: 'آخرین مرحله هرگز پیوند نیست',
    ntTwoControlHeightTargets: 'دو هدف هم\u200cارتفاع با کنترل، نه فلش\u200cهای تنگ',
    ntTypeToFilterEscape: 'برای پالایش بنویسید · Escape برمی\u200cگرداند',
    ntTypingAlwaysWorksThe: 'تایپ\u200cکردن همیشه کار می\u200cکند؛ تقویم فقط کمک است',
    spChartLine: 'خط و ناحیه', spChartBar: 'میله', spSparkline: 'نمودار خطیِ ریز',
    ntChart:
      'نه کتابخانهٔ رسم و نه canvas: یک SVG که از قرارداد کشیده شده. تصویر از فناوری یاری‌رسان پنهان است و عددها کنارش به‌صورت یک جدول واقعی بیرون داده می‌شوند.',
    ntChartBar: 'میله هرچه فراخوان بخواهد به صفر سنجاق است — میلهٔ بریده نسبتی را که می‌کشد بد می‌گوید.',
    ntSparkline: 'روند در اندازهٔ متن. کنار یک عدد می‌آید، هرگز به‌جای آن.',
    chSessions: 'نشست‌ها', chSignups: 'ثبت‌نام', chChurn: 'لغو',
    chTitle: 'نشست‌ها و ثبت‌نام‌ها', chNote: 'هزار، هفت ماه گذشته',
    chBarTitle: 'درآمد به تفکیک منطقه', chBarNote: 'میلیون ریال',
    chEurope: 'اروپا', chAsia: 'آسیا', chAmericas: 'آمریکا',
    spMap: 'یک چیزِ مکان‌دار', ntMap:
      'کیت هیچ ارائه‌دهندهٔ کاشی نمی‌فرستد و هیچ شبکه‌ای باز نمی‌کند — تصویر مالِ محصول است. آنچه مالِ کیت است قاب، سنجاق‌ها، تصویرسازی مختصات و جای انتسابی است که پروانه لازم دارد.',
    mapTitle: 'تهران، منطقهٔ ۶',
    mapOffice: 'استودیو', mapClinic: 'کلینیک فاطمی‌فر', mapYou: 'اینجایی',
    mapAttribution: 'کاشی‌ها © ارائه‌دهندهٔ خودِ محصول',
    spPlayerAudio: 'صوت', spPlayerVideo: 'ویدیو',
    ntPlayer:
      'روی عنصر خودِ پلتفرم ساخته شده، نه به‌جای آن: رمزگشا، کلیدهای رسانه، تصویر-در-تصویر و پخش در پس‌زمینه همه از آنجا می‌آیند. فقط ناوبَر کشیده شده.',
    playerTrack: 'صدای اتاق — استودیو، برداشت ۳',
    playerEpisode: 'جلسهٔ ۰۴ — پاسِ بافت',
  },
  f: {
    introTitle: 'توکن‌ها خودِ سامانه‌اند.',
    introBody:
      'کامپوننت‌ها فقط نام‌های زیر را می‌شناسند. سبک یا پالت رنگ را عوض کنید و همهٔ صفحه‌ها یک‌جا تغییر می‌کنند، چون هیچ‌چیزِ پایین‌دستِ این قرارداد مقدار ثابتی در خود ندارد.',
    colourBody:
      'نقش‌ها، نه مقادیر خام. یک پالت رنگ به همهٔ نام‌های زیر پاسخ می‌دهد؛ سبکی که با آن جفت می‌شود به هیچ‌کدام.',
    surfaces: 'سطح‌ها', ink: 'جوهر', accent: 'تأکید', status: 'وضعیت', lines: 'خط‌ها',
    shadowTint: 'ته‌رنگ سایه',
    shadowTintNote:
      'رنگی که افست‌های سبک با آن کشیده می‌شوند. حالت روشن آن‌ها را با رنگ خط می‌کشد؛ حالت تیره باید سیاه واقعی باشد، وگرنه افست به‌جای عمق مثل هاله دیده می‌شود.',
    typeRoles: 'نقش‌ها',
    typeNote:
      'نقش «برچسب» جایی است که دو سبک بیشترین فاصله را دارند: لجر آن را مونو، بزرگ و با فاصله‌گذاری پهن می‌چیند؛ ولورا با قلم متن و بدون تغییر حروف. نقش «کنترل» از «برچسب» جداست — نوشته‌ای که کنار یک چیز چاپ می‌شود با چیزی که فشارش می‌دهید یک صدا ندارند.',
    displayRole: 'نمایشی', displayLgRole: 'ویرایشی، بزرگ', displayXlRole: 'ادعای صفحه',
    editorialRoles: 'اندازه‌های ویرایشی',
    editorialNote:
      'بالاتر از رده محصول: display-lg یک سند بلند را باز می‌کند و display-xl تنها ادعای یک صفحه است. هر دو text-wrap: balance را کنار می‌گذارند؛ جای شکستن ادعا تصمیم متن است، پس با Display.Line نوشته می‌شود. یک سطر می‌تواند رنگ سیگنال بگیرد و یک سطر می‌تواند از حاشیه خواندن عقب برود.',
    titleLarge: 'عنوان، بزرگ', titleMedium: 'عنوان، متوسط',
    bodyRole:
      'متن بدنه بارِ محتوا را می‌کشد. در عرضی خوانا می‌نشیند و هرگز با عنوان‌های بالای خود رقابت نمی‌کند.',
    labelRole: 'برچسب · امضای سبک', controlRole: 'کنترل · چیزی که دکمه با آن چیده می‌شود',
    captionRole: 'زیرنویس — ثانویه، آرام، و هرگز حامل بار اصلی.',
    spaceBody: 'پایهٔ ۴ پیکسل. کامپوننت‌ها پله‌ها را مصرف می‌کنند، نه پیکسل خام را.',
    sizeTitle: 'اندازه‌های ثابت',
    sizeBody:
      'هندسه‌ای که نه پلهٔ فاصله است و نه ارتفاع کنترل: قطر یک نقطه، ضلع یک آواتار، ضخامت یک ریل. این‌ها تا نسخهٔ ۰٫۲ مقادیر ثابتی درون components.css بودند و هیچ تمی نمی‌توانست پاسخ‌شان بدهد.',
    radius: 'گردی گوشه', radiusNote: 'در لجر گوشه‌تیز، در ولورا گرد',
    elevation: 'ارتفاع', elevationNote: 'در لجر افست سخت، در ولورا سایهٔ نرم',
    focusTitle: 'فوکوس',
    focusBody:
      'یک حلقه، بیرون از جعبه و روی بوم کشیده می‌شود تا روی هر سطحی خوانده شود، و به همهٔ عناصر فوکوس‌پذیر کیت اعمال می‌شود. تا پیش از ۰٫۲ این توکن را همهٔ تم‌ها تعریف می‌کردند و فقط یک قاعده مصرفش می‌کرد، پس پیمایش با Tab هیچ نشانی نداشت.',
    focusHint: 'با Tab میان این‌ها حرکت کنید — حلقه واقعی است، نه تصویری کشیده‌شده.',
    focusInvalid: 'فیلد نامعتبر با رنگ خطا فوکوس می‌گیرد تا حلقه هرگز با پیام زیرش در تضاد نباشد.',
    densityTitle: 'تراکم',
    densityBody:
      'یک ضریب روی مقیاس کنترل‌ها و فاصلهٔ عمودی هر چیز ردیف‌مانند، تا یک صفحهٔ پرداده و یک جریان موبایل همان یک سامانه بمانند، نه همان کامپوننت‌ها با اندازه‌های دستی. هرگز تایپ را مقیاس نمی‌کند و هرگز از کف ۴۴ پیکسلی لمس عبور نمی‌کند.',
    compact: 'فشرده', standard: 'پیش‌فرض', roomy: 'گشاده',
    densityRow: 'فاکتور ۲۲۹۱',
    motionCurves: 'منحنی‌ها',
    motionCurvesNote: 'مسافت یکسان، زمان یکسان — تفاوت فقط در منحنی است',
    play: 'پخش', pause: 'مکث',
    motionDurations: 'مدت‌ها',
    durFast: 'رنگ، حاشیه، فشار. هر چیزی که به اشاره‌گرِ هنوز روی عنصر پاسخ می‌دهد.',
    durBase: 'ورود و خروج: شیت، دیالوگ، توست، منو، کلید.',
    durSlow: 'فقط پیشرفت معین — تنها جایی که بیننده مقدار را می‌پاید، نه حرکت را.',
    motionAssignment: 'تخصیص',
    motionAssignmentBody:
      'یک قاعده منحنی را تعیین می‌کند: چیزی که وارد می‌شود با کاهش شتاب سر جایش می‌نشیند، چیزی که بیننده نگهش داشته با منحنی استاندارد پاسخ می‌دهد، و فقط دو چیز فنر می‌خورند. خروج‌ها همان ورود را با مدت «سریع» معکوس می‌کنند، چون رفتن نباید وقت بیننده را بگیرد.',
    motionReduced: 'کاهش حرکت',
    motionReducedBody:
      'قاعدهٔ فراگیر عمداً همهٔ پاسخ نیست. سه انیمیشن کیت تزئین نیستند — تنها نشانهٔ آن‌اند که کاری در جریان است، و خاموش‌کردن کاملشان بیننده را از تشخیص رابطِ مشغول و رابطِ قفل‌شده ناتوان می‌کند. کاهش حرکت یک تسهیلات دهلیزی است، نه درخواستِ اطلاعات کمتر.',
    reducedOn: 'سیستم شما هم‌اکنون کاهش حرکت را درخواست کرده است — منحنی‌های بالا ثابت نگه داشته شده‌اند و سه مورد زیر همان چیزی است که همچنان دریافت می‌کنید.',
    reducedOff: 'سیستم شما کاهش حرکت را درخواست نکرده است. آن را در سطح سیستم‌عامل روشن کنید تا این صفحه بی‌درنگ واکنش نشان دهد.',
    keepsTurning: 'همچنان می‌چرخد، کندتر — چرخش خودش تمام پیام است.',
    keepsFilling: 'به‌جای لغزیدن پر می‌شود: «در حال کار، با مدت نامعلوم»، بدون حرکت.',
    goesAway: 'تزئین محض. بلوک‌های خاکستری همان چیزی را که باید، می‌گویند.',
    press: 'فشار', hover: 'هاور', focusRing: 'حلقهٔ فوکوس', menuPopover: 'منو · پاپ‌اوور',
    dialogSheet: 'دیالوگ · شیت', toastIn: 'ورود توست', switchThumb: 'دستهٔ کلید',
    progressFill: 'پرشدن پیشرفت', instant: '۰ میلی‌ثانیه — حلقهٔ فوکوس هرگز با انیمیشن نمی‌آید',
  },
  fl: {
    introTitle: 'جریان‌ها',
    introBody:
      'صفحه‌هایی که محصول پیش از استفاده با آن‌ها قضاوت می‌شود: معرفی، ورود، انتخاب اشتراک، پروفایل، و نواری که کل برنامه را حمل می‌کند. همه از دل کیت ساخته شده‌اند — بدون CSS اختصاصی، و همه به کلیدهای سبک، پالت، طرح رنگ و زبانِ بالا پاسخ می‌دهند.',
    spIntro: 'معرفی سه‌صفحه‌ای',
    ntIntro: 'وضعیت از آنِ خودِ اسلایدر است؛ onDone یک‌بار مسیر را تعیین می‌کند، از پایان یا از رد کردن.',
    slide1Label: 'شروع با یک اسکن', slide1Title: 'پوستت را\nحدس نزن',
    slide1Body: 'با یک اسکن کوتاه، نشانه‌های مهم پوستت را واضح‌تر ببین؛ از خشکی و بافت تا درخشندگی و نواحی حساس.',
    slide1Proof: 'تصویری روشن از پوست امروزت', slide1Points: ['اسکن ساده', 'گزارش روشن', 'بدون قضاوت'],
    slide2Label: 'روتین برای امروزت', slide2Title: 'بدان امشب\nدقیقاً چه کار کنی',
    slide2Body: 'به‌جای توصیه‌های پراکنده، فقط قدم‌های لازم را ببین؛ برای صبح، شب و انتخاب محصول مناسب پوستت.',
    slide2Proof: 'مراقبت ساده، قدم‌به‌قدم', slide2Points: ['روتین کوتاه', 'نیازهای اولویت‌دار', 'پیگیری روزانه'],
    slide3Label: 'پیشرفت قابل دیدن', slide3Title: 'تغییر پوستت را\nواقعاً ببین',
    slide3Body: 'اسکن‌ها، روتین‌ها و محصول‌ها در یک مسیر می‌مانند تا بفهمی چه چیزی برای پوستت بهتر جواب می‌دهد.',
    slide3Proof: 'روندی که از دستت درنمی‌رود', slide3Points: ['روند پوست', 'مقایسهٔ اسکن‌ها', 'انتخاب آگاهانه'],
    next: 'ادامه بده', finish: 'شروع مراقبت شخصی', signIn: 'ورود',
    version: 'نسخهٔ ۰٫۳٫۰',
    spPhone: 'گام شماره', spOtp: 'گام کد', spPassword: 'گام گذرواژه',
    ntPhone: 'کشور و رقم‌های ملی دو پراپ جدا هستند؛ toE164 آن‌ها را به هم می‌چسباند.',
    ntOtp: 'یک رشته، نه پنج جعبهٔ وضعیت. چسباندن و تکمیل خودکار پیامک از یک مسیر می‌گذرند.',
    ntPassword: 'امتیازدهی با فراخوان است: سنجه‌ای که با سرور نخواند، از نبودنش بدتر است.',
    welcome: 'خوش آمدی', welcomeBody: 'شماره موبایلت را وارد کن.\nکد تأیید می‌فرستیم — بدون گذرواژه.',
    phoneLabel: 'شمارهٔ موبایل', sendCode: 'ارسال کد تأیید',
    terms: 'با ادامه، با قوانین استفاده و حریم خصوصی موافقی.',
    codeTitle: 'کد تأیید', codeBody: 'کد ۵ رقمی ارسال‌شده به این شماره را وارد کن',
    codeLabel: 'کد تأیید', digit: 'رقم', verify: 'تأیید و ورود',
    resendIn: 'ارسال مجدد تا ۴۲ ثانیهٔ دیگر', back: 'بازگشت',
    passwordTitle: 'ورود با گذرواژه', passwordBody: 'ایمیل و گذرواژهٔ حسابت را وارد کن.',
    emailLabel: 'ایمیل', passwordLabel: 'گذرواژه', forgot: 'گذرواژه‌ات را فراموش کرده‌ای؟',
    signInAction: 'ورود', useCode: 'به‌جایش با کد تأیید وارد شو',
    spPlans: 'انتخاب اشتراک', spBilling: 'دورهٔ پرداخت',
    ntPlans: 'کل کارت خودِ کنترل است، و قیمت یک نود است — واحد پول و شکل رقم‌ها تصمیم محلی محصول است.',
    free: 'رایگان', plus: 'پلاس', pro: 'پرو',
    freeTag: 'شروعی هوشمندانه', plusTag: 'هوش مصنوعی در خدمت پوست تو', proTag: 'همه‌چیز، با بیشترین ظرفیت',
    recommended: 'پیشنهاد ما', mostCapacity: 'بیشترین ظرفیت',
    perPack: 'هزینهٔ این بسته', perMonth: 'ماهانه', soon: 'به‌زودی',
    fFree1: '۳ اسکن ساده در ماه', fFree2: 'گزارش پایهٔ پوست', fFree3: 'نگهداری یک‌هفته‌ای اسکن',
    fFree4: 'روتین شخصی‌سازی‌شده', fFree5: 'تحلیل پیشرفتهٔ هوش مصنوعی',
    fPlus1: 'اسکن ساده نامحدود', fPlus2: '۴ اسکن پیشرفته در ماه', fPlus3: 'روتین شخصی‌سازی‌شده',
    fPlus4: 'پیشنهاد محصول', fPlus5: 'بازبینی متخصص',
    oneMonth: '۱ ماهه', threeMonths: '۳ ماهه', sixMonths: '۶ ماهه', save: '۱۵٪ تخفیف',
    spProfile: 'سربرگ پروفایل', ntProfile: 'یک سربرگ است، نه داشبورد — هرچه نمودار می‌خواهد، پایین‌تر می‌نشیند.',
    account: 'حساب vlora', person: 'سارا احمدی',
    completion: 'تکمیل پروفایل', scans: 'اسکن‌ها', streak: 'روز متوالی',
    skinChip: 'پوست مختلط', planChip: 'پلاس · ۶ ماهه',
    completeProfile: 'تکمیل پروفایل پوست', seeAnalysis: 'دیدن تحلیل پوست',
    spSignIn: 'کل مسیر ورود',
    ntSignInFlow:
      'آماده‌ی نصب، نه سرِ هم‌کردنی: ماشین گام‌ها، شمارش معکوس ارسال دوباره و حالت‌های خطا از آنِ خود کامپوننت‌اند. این نمونه کد ۱۲۳۴۵ را می‌پذیرد.',
    wrongCode: 'این کد درست نیست. دوباره بررسی کن.',
    signInCopy: {
      back: 'بازگشت',
      codeLabel: 'کد تأیید',
      codeSubtitle: (destination: string) => `کد ۵ رقمی ارسال‌شده به ${destination} را وارد کن`,
      codeTitle: 'کد تأیید',
      identifierLabel: 'ایمیل',
      passwordLabel: 'گذرواژه',
      passwordSubtitle: 'ایمیل و گذرواژهٔ حسابت را وارد کن.',
      passwordTitle: 'ورود با گذرواژه',
      phoneLabel: 'شمارهٔ موبایل',
      phoneSubtitle: 'شماره موبایلت را وارد کن. کد تأیید می‌فرستیم — بدون گذرواژه.',
      phoneTitle: 'خوش آمدی',
      resend: 'ارسال دوبارهٔ کد',
      resendIn: (seconds: number) => `تا ${seconds} ثانیهٔ دیگر می‌توانی کد تازه بخواهی`,
      sendCode: 'ارسال کد تأیید',
      signIn: 'ورود',
      usePassword: 'به‌جایش با گذرواژه وارد شو',
      usePhone: 'به‌جایش با کد تأیید وارد شو',
      verify: 'تأیید و ورود',
    },
    spChat: 'متن، صوت، ویدیو، فایل',
    ntChat:
      'رسانه با عنصرهای خودِ پلتفرم پخش می‌شود. کامپوزر هرجا مرورگر اجازه دهد صدا ضبط می‌کند و هم نشانی‌ها و هم فایل‌ها را به فراخوان می‌دهد.',
    chatPresence: 'آنلاین',
    chatPlaceholder: 'پیامت را بنویس',
    chat1: 'صبح بخیر — روتین شب تازه رسید؟',
    chat2: 'رسید. از امشب شروع می‌کنم و جمعه یک اسکن می‌فرستم.',
    chat3: 'دو ثانیه از بافت گونه‌ام.',
    chat4: 'یادداشت‌های جلسهٔ قبل پیوست است.',
    chatLabels: {
      deleted: 'پیام حذف شد',
      download: 'دانلود',
      edited: 'ویرایش‌شده',
      failed: 'ارسال نشد',
      more: 'کنش‌های پیام',
      pause: 'مکث',
      play: 'پخش',
      react: 'واکنش',
      read: 'خوانده شد',
      reply: 'پاسخ',
      sending: 'در حال ارسال',
      sent: 'ارسال شد',
      today: 'امروز',
      typing: 'در حال نوشتن است',
      yesterday: 'دیروز',
      voiceMessage: 'پیام صوتی',
    },
    composerLabels: {
      attach: 'پیوست فایل',
      cancel: 'لغو ضبط',
      cancelReply: 'لغو پاسخ',
      discard: 'حذف پیوست',
      record: 'ضبط پیام صوتی',
      recording: 'در حال ضبط',
      replyingTo: 'پاسخ به',
      send: 'ارسال',
      stop: 'پایان و پیوست',
      video: 'پیوست ویدیو',
    },
    ntPlanPicker:
      'انتخاب را نگه می‌دارد، دوره و قیمت‌ها را هم‌گام می‌کند، و به onSubmit همان جفتی را می‌دهد که پرداخت لازم دارد.',
    continueToPayment: 'ادامه به پرداخت',
    planNote: 'مبلغ نهایی پیش از پرداخت نمایش داده می‌شود.',
    ntProfileScreen: 'ردیف‌ها داده‌اند — یک برچسب، یک آیکون، و یا مقصدی برای رفتن یا کلیدی برای زدن.',
    groupAccount: 'حساب', groupPreferences: 'ترجیح‌ها', groupApp: 'برنامه',
    rowPersonal: 'مشخصات فردی', rowSkin: 'پروفایل پوست', rowPlan: 'اشتراک',
    rowNotifications: 'اعلان‌ها', rowNotificationsSub: 'هر روز ساعت ۸ صبح',
    rowReduced: 'کاهش حرکت', rowVersion: 'نسخه', rowDelete: 'حذف حساب',
    signOut: 'خروج از حساب',
    ntAppShell: 'یک ناحیهٔ اسکرول، و محتوایی که جای نوارِ شناور را کنار می‌گذارد. از ۶۴rem به بالا همین قاب باز می‌شود و نوار تب‌ها ریل کناری می‌شود؛ این نمونه چون در جعبه‌ای به اندازهٔ موبایل است، قاب موبایل را ثابت نگه می‌دارد.',
    shellBody: 'صفحه اینجا اسکرول می‌شود. نوار بالای ناحیهٔ امن شناور است و محتوای زیرش پَد دارد، نه اینکه پنهان شود.',
    spWizard: 'هر صفحه، یک پرسش',
    ntWizard:
      'شمارهٔ گام از آنِ ویزارد است؛ پاسخ‌ها نه. هر گام فقط می‌گوید که می‌تواند ادامه دهد یا نه.',
    wizardQ1: 'امروز چطور بود؟', wizardS1: 'یک ضربه کافی است. بعداً هم می‌توانی عوضش کنی.',
    wizardQ2: 'چه چیزی شکلش داد؟', wizardS2: 'تا سه مورد انتخاب کن.',
    wizardQ3: 'چیزی هست که بماند؟', wizardS3: 'یک خط کافی است.',
    moodBad: 'بد', moodLow: 'کم', moodOk: 'معمولی', moodGood: 'خوب', moodGreat: 'عالی',
    causeWork: 'کار', causeFamily: 'خانواده', causeSleep: 'خواب', causeHealth: 'سلامت',
    causeFriends: 'دوستان', causeOutdoors: 'بیرون',
    notePlaceholder: 'امروز متوجه شدم…', wizardDone: 'ثبت یادداشت',
    spCheckout: 'خلاصهٔ سفارش و پرداخت',
    ntCheckout:
      'هر عدد، نودی است که فراخوان قالب‌بندی کرده. پول آخرین چیزی است که یک کیت رابط باید گرد کند.',
    payWith: 'روش پرداخت', gatewayCard: 'کارت بانکی', gatewayCardDesc: 'پرداخت آنلاین، تأیید فوری',
    gatewayTransfer: 'کارت به کارت', gatewayTransferDesc: 'ارسال رسید برای بررسی',
    gatewayReview: 'بررسی دستی', gatewayDefault: 'سریع‌ترین',
    gatewayDetail: 'IR62 0170 0000 0011 2345 6789',
    orderTitle: 'چه چیزی می‌خری',
    linePlan: 'اشتراک پلاس', linePlanMeta: '۶ ماهه · تمدید ۱۴۰۵/۱۲/۰۱',
    lineScan: 'اعتبار اسکن پیشرفته', lineScanMeta: '۴ اعتبار',
    subtotal: 'جمع جزء', tax: 'مالیات (۹٪)', fee: 'کارمزد درگاه', totalLabel: 'مجموع',
    payNow: 'پرداخت', payNote: 'مبلغ نهایی را درگاه پیش از تأیید نشان می‌دهد.',
    spProgress: 'کاری با مرحله‌های نام‌دار',
    ntProgress:
      'مرحله‌ها اصل ماجرا هستند: درصد می‌گوید چقدر صبر کن، مرحلهٔ نام‌دار می‌گوید کدام بخش شکست خورد.',
    scanTitle: 'در حال تحلیل اسکن', scanCaption: 'معمولاً کمتر از یک دقیقه طول می‌کشد.',
    stepUpload: 'بارگذاری تصویر', stepQuality: 'بررسی کادر و نور',
    stepAnalyse: 'خواندن نشانه‌های پوست', stepRoutine: 'ساخت روتین',
    stepReport: 'نوشتن گزارش',
    stepFailedDetail: 'ناحیهٔ گونه بیش از حد تاریک است — در نور روز دوباره بگیر.',
    cancelJob: 'لغو', stepsOf: (done: number, total: number) => `${done} از ${total} مرحله`,
    stepStatus: {
      active: 'در حال انجام',
      done: 'انجام شد',
      failed: 'ناموفق',
      pending: 'در انتظار',
      skipped: 'رد شد',
    },
    spConsole: 'صفحه، پنل، سنجه، مشخصات', spConsoleTable: 'جدول داده',
    ntConsole:
      'قطعه‌هایی که زیر پوستهٔ کنسول می‌نشینند. هر کنسول نسخهٔ خودش را از ظرف صفحه، بخش عنوان‌دار، ردیف شمارنده و بلوک برچسب/مقدار ساخته بود؛ اینها همان‌ها هستند، روی قرارداد توکن.',
    ntConsoleTable:
      'یک مؤلفه چهار حالت هر فهرست از راه دور را حل می‌کند — خطا، بار اول، خالی، ردیف‌ها — به همین ترتیب.',
    csRequests: 'درخواست‌ها', csErrors: 'نرخ خطا', csLatency: 'تأخیر p95', csQueue: 'عمق صف',
    csFleet: 'وضعیت ناوگان', csSince: 'نسبت به دیروز', csDeploy: 'گزارش استقرار',
    csHost: 'میزبان', csRegion: 'ناحیه', csImage: 'ایمیج', csUptime: 'زمان کارکرد',
    csHealthy: 'سالم', csDegraded: 'کاهش‌یافته', csDraining: 'در حال تخلیه',
    csNode: 'گره', csState: 'حالت', csTasks: 'وظیفه‌ها', csEmpty: 'گره‌ای گزارش نشد',
    csEmptyBody: 'خوشهٔ انتخاب‌شده فهرست خالی برگرداند.',
    spBrand: 'قفل‌شدهٔ برند و نشان‌های سازنده',
    ntBrand:
      'هر کنسول این خانواده همان ردیف فلکس، جعبهٔ نشان، نام و شعار را جداگانه نوشته بود — و نسخه‌ها بر سر فاصله، رنگ شعار و اینکه نام عنوان است یا متن، هم‌نظر نبودند. `Brand` همان شیء است، یک‌بار؛ و `nameAccent` رنگ خودِ محصول را از یک متغیر می‌گیرد، پس نشان‌واژهٔ دو رنگ به‌جای یک مقدار مستقیم، یک متغیر هزینه دارد. `BrandMark` عمداً فهرستی جدا از `Icon` است: آیکون نقش باید در همهٔ صفحه‌ها یک معنا بدهد، نشان سازنده دقیقاً یک محصول را می‌گوید.',
    brandTagline: 'کنترل‌پلین از راه دور داکر سوارم',
    spProcedure: 'ریل مرحله‌ها، ریل کناری، تراشهٔ کپی',
    ntProcedure:
      'یک رویهٔ کنسولی که در پنج بخش پخش شده است: مرحله‌هایی که طی می‌شود، پنل‌های شماره‌دار که هر تصمیم را جمع می‌کنند، و ریل چسبانی که کل نقشه در آن بازخوانی و تأیید می‌شود. کنش فقط از همان ریل صادر می‌شود.',
    prStages: 'ارائه‌دهنده', prStages2: 'مخزن', prStages3: 'کشف', prStages4: 'بازبینی', prStages5: 'استقرار',
    prConnect: 'اتصال منبع', prSelect: 'انتخاب و تأیید', prScan: 'پویش و شواهد',
    prClassify: 'دسته‌بندی و نگاشت', prConfigure: 'پیکربندی و استقرار',
    prPlan: 'نقشهٔ استقرار', prApps: 'برنامه‌ها', prImages: 'ایمیج‌ها (تغییرناپذیر)',
    prWarnings: 'هشدارها', prBlockers: 'بازدارنده‌ها', prDeploy: 'استقرار',
    prBlocked: 'برای فعال شدن استقرار، بازدارنده‌ها را برطرف کنید',
    prWarning: 'فایل Compose در /services/worker از تگ latest استفاده می‌کند',
    prBlocker: 'سرویس worker بررسی سلامت ندارد',
    prProviderBody: 'یک اتصال تأییدشده مثل یک رکورد خوانده می‌شود؛ فرم تنها وقتی برمی‌گردد که چیزی برای افزودن یا جایگزینی باشد.',
    spAdmin: 'چیدمان پنل', spDetail: 'سربرگ رکورد', spFilters: 'فیلترهای فعال', spFeed: 'فعالیت',
    ntAdmin:
      'همتای AppShell است، نه گونه‌ای از آن: دو ستون، سلسله‌مراتب عمیق، و همان نوار کناری که زیر نقطهٔ شکست به کشو تبدیل می‌شود.',
    ntDetail: 'کنش‌ها بالا می‌نشینند، جایی که اپراتورِ صف بدون خواندن کل رکورد تصمیم می‌گیرد.',
    ntFeed: 'زمان مطلق: دنبالهٔ رویدادها را باید بازسازی کرد.',
    navOverview: 'نمای کلی', navCommerce: 'فروش', navMonitoring: 'نظارت',
    navDashboard: 'داشبورد', navUsers: 'کاربران', navOrders: 'سفارش‌ها', navPayments: 'پرداخت‌ها',
    navQueues: 'صف‌ها', navScans: 'اسکن‌ها', navSettings: 'تنظیمات',
    adminSession: 'نشست فعال', adminBuild: 'نسخهٔ ۰٫۶٫۰',
    paymentTitle: 'پرداخت ۴۸۲۱۰', paymentSubtitle: 'رسید دستی · پلاس، ۶ ماهه',
    paymentMeta: 'آخرین بروزرسانی ۲ شهریور، ۰۹:۴۱', paymentStatus: 'در انتظار بررسی',
    approve: 'تأیید', reject: 'رد', backToPayments: 'پرداخت‌ها',
    filterStatus: 'وضعیت', filterPending: 'در انتظار', filterGateway: 'درگاه',
    filterManual: 'رسید دستی', filterRange: 'بازه', filterThisWeek: 'این هفته',
    clearAll: 'پاک کردن همه',
    feed1: 'پرداخت را تأیید کرد', feed2: 'رسید را رد کرد', feed3: 'اشتراک را تغییر داد برای',
    feed4: 'گفت‌وگوی پشتیبانی باز کرد با',
    actorNima: 'نیما', actorSara: 'سارا', targetPayment: '۴۸۲۱۰', targetUser: 'کاربر ۳۳۹۱',
    spTabBar: 'ناوبری پایین', ntTabBar: 'مسیریابی بیرون می‌ماند: renderItem پراپ‌ها را به Link خودِ اپ می‌دهد.',
    tabHome: 'خانه', tabRoutine: 'روتین', tabScan: 'اسکن', tabReflect: 'بازتاب', tabProfile: 'پروفایل',
    spMessenger: 'کانال‌ها، گروه‌ها، خصوصی',
    ntMessenger:
      'روی جعبهٔ پهن دو ستون، روی باریک یکی — و کلیدِ تغییر یک container query است، چون مسنجر معمولاً درون چیز دیگری جاسازی می‌شود.',
    mgChannels: 'کانال‌ها', mgGroups: 'گروه‌ها', mgDirect: 'خصوصی',
    mgSearch: 'جست‌وجوی گفت‌وگوها',
    mgCompose: 'گفت‌وگوی تازه',
    mgMembersWord: 'عضو',
    roomShip: 'ship-room', roomDesign: 'design-review', roomIncidents: 'incidents',
    groupClinic: 'تیم کلینیک', groupLaunch: 'گروه انتشار',
    personAmir: 'امیر تهرانی', personLeila: 'لیلا روشن',
    mgOnline: 'سارا، امیر و ۴ نفر دیگر',
    mgPreviewShip: 'امیر: امشب ۰٫۹ را تگ می‌زنم',
    mgPreviewDesign: 'لیلا: دنباله فقط روی آخرین حباب',
    mgPreviewIncidents: 'حل شد — edge-2.fra برگشت به چرخه',
    mgPreviewClinic: 'شما: یادداشت‌ها پیوست است',
    mgPreviewLaunch: 'لیلا: نقشه حالا درست است',
    mgPreviewSara: 'پیام صوتی · ۰:۰۳',
    mgPreviewAmir: 'در حال نوشتن…',
    spGroup: 'یک گروه، با هرچه یک پیام می‌تواند بکند',
    ntGroup:
      'پیام‌های پشت‌سرهمِ یک نفر یک «دور» است: یک آواتار، یک نام، یک زمان، و دنباله فقط روی آخرین حباب.',
    gm1: 'امروز صبح رونوشت را باز کردم. «دور» تمام تفاوت است — چهار حباب از یک نفر باید یک نوبت خوانده شود.',
    gm2: 'موافقم. و دنباله فقط روی آخری.',
    gm3: 'ترافیک این هفته، چون بالاخره کسی در جلسه می‌پرسد:',
    gm4: 'آن افت پنجشنبه استقرار است، نه پس‌رفت.',
    gm5: 'قرار جمعه — ورودی کلینیک، نه در اصلی.',
    gm6: 'یادداشت شد. ساعت نه آنجایم.',
    gm7: 'این هم صدای اتاقِ استودیو.',
    gm8: 'این یکی را اشتباهی فرستادم.',
    gmSystem: 'لیلا امیر را به گروه اضافه کرد',
    gmChartTitle: 'نشست‌های این هفته',
    gmChartNote: 'هزار، همهٔ مناطق',
    gmMapTitle: 'ورودی کلینیک',
    gmMapAttribution: 'کاشی‌ها © ارائه‌دهندهٔ خودِ محصول',
    acReply: 'پاسخ', acCopy: 'رونوشت متن', acForward: 'هدایت', acPin: 'سنجاق', acDelete: 'حذف',
    spAssistant: 'گفت‌وگو با دستیار',
    ntAssistant:
      'حباب نیست: یک پاسخ سند است، و سند در حباب نمی‌رود. فقط نوبتِ خودِ بیننده سطح نگه می‌دارد.',
    asName: 'دستیار nim',
    asPlaceholder: 'هرچه می‌خواهی بپرس',
    asQ1: 'چرا p99 از سه‌شنبه بالا رفته؟',
    asA1Lead: 'سه‌شنبه دو اتفاق افتاد و فقط یکی‌شان مالِ شماست.',
    asA1Body:
      'استقرار ۰۹:۴۰ تغییر اندازهٔ تصویر را روی مسیر درخواست برد، که حدود ۴۰ میلی‌ثانیه به میانه و بسیار بیشتر به دنباله افزود. جدا از آن، edge-2.fra سه ساعت بعدازظهر از چرخه بیرون رفت و گرهٔ باقی‌مانده تمام بار آن منطقه را برداشت.',
    asA1Tail: 'کاری که باید کرد با استقرار است. گره خودش برگشته.',
    asStep1: 'خواندن گزارش استقرار', asStep2: 'پرس‌وجوی تأخیر به تفکیک منطقه', asStep3: 'مقایسه با هفتهٔ پیش',
    asStepDetail: '۲ منطقه · ۱۴ روز',
    asSource1: 'استقرار ۴۸۲۱ — یادداشت انتشار',
    asSource2: 'p99 به تفکیک منطقه، ۱۴ روز',
    asEmptyTitle: 'دربارهٔ سامانه بپرس',
    asEmptyBody: 'گزارش استقرار، سنجه‌ها و سابقهٔ رخداد را می‌خواند و می‌گوید کدام‌شان پرسش تو را توضیح می‌دهد.',

  },
  clients: ['آتلیه فاطمی‌فر', 'کانون وکلای ایران', 'ریل‌فورج', 'ولورا', 'استودیو نیم'],
}

export const COPY: Record<Lang, typeof en> = { en, fa }
